python diode_clipper/visualize_ode.py diode_clipper/runs/diodeclip/forward_euler/July13_07-49-07_axel_ODENet2Hidden100
python diode_clipper/visualize_ode.py diode_clipper/runs/diodeclip/forward_euler/July16_13-14-04_axel_ODENet2Hidden9
python diode_clipper/visualize_ode.py diode_clipper/runs/diodeclip/odeint_implicit_adams/August04_12-16-11_axel
python diode_clipper/visualize_analytical_ode.py
